puddle/conf/urls.py
from django.contrib import admin
from django.urls import path, include

from core import urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('', include('item.urls'))
]

puddle/core/urls.py
from django.urls import path
from . import views
from .forms import LoginForm
from django.contrib.auth import views as auth_views
# from item.views import detail
from django.conf import settings
from django.conf.urls.static import static

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
    path('about/', views.about, name='about'),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='login.html', authentication_form=LoginForm), name='login'),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

puddle/item/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'item'

urlpatterns = [
    path('<int:pk>/', views.detail, name='detail'),
    path('new/', views.new_item, name='new'),
]

puddle/core/models.py
from django.db import models

puddle/item/models.py
from django.db import models
from django.contrib.auth.models import User


class Catergory(models.Model):
    name = models.CharField(max_length=255)

    class Meta:
        ordering = ('name',)
        verbose_name_plural = 'Categories'  #django model automatic find name of model that's why we rename by verbose_name_plural to 'extra-name'

    def __str__(self):
        return self.name


class Item(models.Model):
    category = models.ForeignKey(Catergory, related_name='items', on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    price = models.FloatField()
    image = models.ImageField(upload_to='item_image', blank=True, null=True)
    is_sold = models.BooleanField(default=False)
    created_by = models.ForeignKey(User, related_name='items', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

puddle/core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User


class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your username',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))

    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Your password',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))

class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your usernmae',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'placeholder': 'Your email address',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Your password',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Repeat password',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))

puddle/item/forms.py
from django import forms
from .models import Item

class NewItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ('category', 'name', 'description', 'price', 'image',)

    category = forms.ChoiceField(widget=forms.Select(attrs={
        'class': 'w-full py-4 px-6 rounded-xl'
    }))

    name = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'name of product',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))

    description = forms.CharField(widget=forms.Textarea(attrs={
        'placeholder': 'description of product',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))

    price = forms.FloatField(widget=forms.NumberInput(attrs={
        'placeholder': 'price of item',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))

    image = forms.ImageField(widget=forms.FileInput(attrs={
        'class': 'w-full py-4 px-6 rounded-xl'
    }))

puddle/core/views.py
from django.shortcuts import render, redirect
from item.models import Catergory, Item

from .forms import SignupForm

def index(request):
    items = Item.objects.filter(is_sold=False)[:6]
    categories = Catergory.objects.all()
    context = {
        'categories': categories,
        'items': items,
    }
    return render(request, 'index.html', context)


def contact(request):
    return render(request, 'contact.html')


def about(requset):
    return render(requset, 'about.html')


# def login(request):
#     return render(request, 'login.html')
#

def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/login/')
    else:
        form = SignupForm()
    context = {
        'form': form,
    }
    return render(request, 'signup.html', context)

puddle/item/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required

from .models import Item, Catergory
from .forms import NewItemForm


def detail(request, pk):
    item = get_object_or_404(Item, pk=pk)
    related_items = Item.objects.filter(category=item.category, is_sold=False).exclude(pk=pk)[0:3]
    context = {
        'item': item,
        'related_items': related_items,
    }
    return render(request, 'detail.html', context)


@login_required('login/')
def new_item(request):
    form = NewItemForm()
    context = {
        'form': form,
        'title': 'New Item',
    }
    return render(request, 'form.html', context)

puddle/core/templates/about.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

puddle/core/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <script src="https://cdn.tailwindcss.com"></script>
    <title>{% block title %}{% endblock %}</title>
</head>
<body>

    <nav class="py-6 px-6 flex justify-between items-center border-b border-gray-200">
        <a href="/" class="text-xl font-semibold">Puddle</a>
        <div class="space-x-6">
            <a href="{% url 'item:new' %}" class="text-lg font-semibold hover:text-gray-500">New item</a>
            <a href="#" class="text-lg font-semibold hover:text-gray-500">Browse</a>
            {% if request.user.is_authenticated %}
                <a href="#" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Inbox</a>
                <a href="#" class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">Dashboard</a>
            {% else %}
                <a href="{% url 'core:signup' %}" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Sign up</a>
                <a href="{% url 'core:login' %}" class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">Login</a>
            {% endif %}
        </div>
    </nav>

    <div class="px-6 py-6">
        {% block content %}
        {% endblock %}
    </div>

    <footer class="py-6 px-6 flex justify-between bg-gray-800">
        <div class="w-2/3 pr-10">
            <h3 class="mb-5 font-semibold text-gray-400">About</h3>
            <p class="text-lg text-gray-500">
                Lorem Ipsum - это текст-"рыба", часто используемый в печати и вэб-дизайне.
                Lorem Ipsum является стандартной "рыбой" для текстов на латинице с начала XVI века.
                В то время некий безымянный печатник создал большую коллекцию размеров и форм шрифтов,
                используя Lorem Ipsum для распечатки образцов. Lorem Ipsum не только успешно пережил
                без заметных изменений пять веков, но и перешагнул в электронный дизайн.
            </p>
        </div>
        <div class="w-1/3">
            <h3 class="mb-5 font-semibold text-gray-400">Menu</h3>
            <ul class="space-y-2">
                <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">About</a></li>
                <li><a href="{% url 'core:contact' %}" class="text-lg text-teal-500 hover:text-teal-700">Contact</a></li>
                <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">Privacy policy</a></li>
                <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">Terms of use</a></li>
            </ul>
        </div>
    </footer>
</body>
</html>

puddle/core/templates/contact.html
{% extends 'base.html' %}

{% block title %} Contact page {% endblock %}

{% block content %}
    <h1> Contact page </h1>
{% endblock%}

puddle/core/templates/index.html
{% extends 'base.html' %}

{% block title %} welcome to Store {% endblock %}

{% block content %}
    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl text-center">Newest item</h2>
        <div class="grid grid-cols-3 gap-3">
            {% for item in items %}
            <div class="bg-white shadow-lg rounded-lg overflow-hidden">
                <a href="{% url 'item:detail' item.id %}">
                    <div class="h-64 w-full">
                        <img src="{{ item.image.url }}" class="w-full h-full object-cover">
                    </div>
                    <div class="p-10">
                        <h2 class="text-xl font-bold">{{ item.name }}</h2>
                        <p class="text-gray-500">Price: {{ item.price }}</p>
                    </div>
                </a>
            </div>
            {% endfor %}
        </div>
    </div>
    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
            <h2 class="mb-12 text-2xl text-center">Categories</h2>
            <div class="grid grid-cols-3 gap-3">
                {% for category in categories %}
                <div class="bg-white shadow-lg rounded-lg overflow-hidden">
                <a href="#">
                    <div class="p-10">
                        <h2 class="text-xl font-bold">{{ category.name }}</h2>
                        <p class="text-gray-500">{{ category.items.count }} Items</p>
                    </div>
                </a>
            </div>
                {% endfor %}
            </div>
    </div>
{% endblock%}

puddle/core/templates/login.html
{% extends 'base.html' %}

    {% block title %} Log in {% endblock %}

{% block content %}

    <div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
        <h1 class="mb-6 text-3xl"> Log in</h1>

        <form method="post" action="." >
            {% csrf_token %}
            <div class="mb-3">
                <label class="inline-block mb-2">Username</label><br>
                    {{ form.username }}
            </div>
            <div class="mb-3">
                <label class="inline-block mb-2">Password</label><br>
                    {{ form.password }}
            </div>
            {% if form.errors or form.non_field_errors %}
                <div class="mb-3 p-6 bg-red-100 rounded-xl">
                    {% for field in form %}
                        {{ field.errors }}
                    {% endfor %}

                    {{ form.non_field_errors }}
                </div>
            {% endif%}
            <button class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Submit</button>
        </form>
    </div>
{% endblock %}

puddle/core/templates/signup.html
{% extends 'base.html' %}

    {% block title %} Sign UP {% endblock %}

{% block content %}

    <div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
        <h1 class="mb-6 text-3xl"> Sign up</h1>

        <form method="post" action="." >
            {% csrf_token %}
            <div class="mb-3">
                <label class="inline-block mb-2">Username</label><br>
                    {{ form.username }}
            </div>
            <div class="mb-3">
                <label class="inline-block mb-2">Email</label><br>
                    {{ form.email }}
            </div>
            <div class="mb-3">
                <label class="inline-block mb-2">Password</label><br>
                    {{ form.password1 }}
            </div>
            <div class="mb-3">
                <label class="inline-block mb-2">Repeat password</label><br>
                    {{ form.password2 }}
            </div>

            {% if form.errors or form.non_field_errors %}
                <div class="mb-3 p-6 bg-red-100 rounded-xl">
                    {% for field in form %}
                        {{ field.errors }}
                    {% endfor %}

                    {{ form.non_field_errors }}
                </div>
            {% endif%}
            <button class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Submit</button>
        </form>
    </div>
{% endblock %}

puddle/item/templates/detail.html
{% extends 'base.html' %}

{% block title %} {{ item.name }} {% endblock %}

{% block content %}
    <div class="grid grid-cols-5 gap-6">
        <div class="col-span-3 object-fill h-48 w-96">
            <img src="{{ item.image.url }}" class="rounded-xl">
        </div>
        <div class="col-span-2 p-6 bg-gray-100 rounded-xl border border-sky-500 shadow shadow-blue-500/40 hover:shadow-indigo-500/200">
            <h1 class="mb-6 text-3xl">{{ item.name }}</h1>
            <div class="bg-cyan-500 shadow-lg shadow-cyan-500/50 rounded-xl transition ease-in-out delay-150 bg-blue-500 hover:-translate-y-1 hover:scale-110 hover:bg-indigo-500 duration-250 p-4">
                <h1 class="text-3xl">Price: {{ item.price }}</h1>
                <h1 class="text-red-500">Seller: {{item.created_by.username }}</h1>
                {% if not item.is_sold %}
                    <h3>Status: Tovar mavjud 😘</h3>
                {% else %}
                    <h3>Status: Tovar sotilgan 🥲</h3>
                {% endif %}
            </div>
            <br>
            {% if item.description %}
            <div class="p-6 shadow-lg shadow-cyan-500/50 rounded-xl transition ease-in-out delay-150 bg-cyan-500 hover:-translate-y-1 hover:scale-110 hover:bg-sky-400 duration-250">
                <h4 class="mb-3 text-xl">{{ item.description }}</h4>
            </div>
            {% endif %}

            <a href="#" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Contact seller</a>
        </div>
    </div>
<div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl text-center">Related items</h2>
        <div class="grid grid-cols-3 gap-3">
            {% for item in related_items %}
            <div class="bg-white shadow-lg rounded-lg overflow-hidden">
                <a href="{% url 'item:detail' item.id %}">
                    <div class="h-64 w-full">
                        <img src="{{ item.image.url }}" class="w-full h-full object-cover">
                    </div>
                    <div class="p-10">
                        <h2 class="text-xl font-bold">{{ item.name }}</h2>
                        <p class="text-gray-500">Price: {{ item.price }}</p>
                    </div>
                </a>
            </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

puddle/item/templates/form.html
{% extends 'base.html' %}

{% block title %} {{ title }} {% endblock %}

{% block content %}

<h1 class="mb-6 text-3xl">{{title}}</h1>

<form method="post" action="." enctype="multipart/form-data">
    {% csrf_token %}
    <div class="space-y-4">
        {{ form.as_p }}
    </div>
    {% if form.errors or form.non_field_errors %}
        <div class="mb-3 p-6 bg-red-100 rounded-xl">
            {% for field in form %}
                {{ field.errors }}
            {% endfor %}
            {{ form.non_field_errors }}
        </div>
    {% endif%}
    <button class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Submit</button>
</form>

{% endblock%}